library aveoplayer;

import 'dart:async';
import 'dart:convert';
import 'dart:developer';
import 'dart:io';

import 'package:flutter/foundation.dart';
import 'package:meta/meta.dart';
import 'package:youtube_player_flutter/youtube_player_flutter.dart';
export 'package:youtube_player_flutter/youtube_player_flutter.dart';
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:flutter_inappwebview/flutter_inappwebview.dart';
import 'package:aveoplayer/vid/video_player_util.dart';
import 'package:aveoplayer/vid/vimeo/custom/helper/print_progress.dart';
import 'package:video_player/video_player.dart';
export 'package:video_player/video_player.dart';
import 'package:webview_flutter/webview_flutter.dart' as webview;
import 'package:http/http.dart' as http;
part 'package:aveoplayer/vid/videoplayer/video_player.dart';
part 'package:aveoplayer/vid/facebook/embed/ios.dart';
part 'package:aveoplayer/vid/facebook/embed/android.dart';
part 'package:aveoplayer/vid/vimeo/embed/android.dart';
part 'package:aveoplayer/vid/vimeo/embed/ios.dart';
part 'package:aveoplayer/vid/vimeo/custom/helper/vimeo.dart';
part 'package:aveoplayer/vid/videoplayer/widgets/custom_tracker_shape.dart';
part 'package:aveoplayer/vid/videoplayer/widgets/video_stack.dart';
part 'package:aveoplayer/vid/videoplayer/widgets/defaults/bottom_controls.dart';
part 'package:aveoplayer/vid/videoplayer/widgets/defaults/default_error.dart';
part 'package:aveoplayer/vid/videoplayer/widgets/defaults/default_loading.dart';
part 'package:aveoplayer/vid/videoplayer/state/player_state.dart';
part 'package:aveoplayer/vid/videoplayer/extension/extension.dart';
part 'package:aveoplayer/vid/videoplayer/widgets/playback_speed.dart';
part 'package:aveoplayer/vid/vimeo/custom/helper/vimeo_video.dart';
part 'package:aveoplayer/vid/vimeo/custom/helper/vimeo_error.dart';
part 'package:aveoplayer/vid/vimeo/custom/helper/remote/auth_api_service.dart';
part 'package:aveoplayer/vid/vimeo/custom/helper/remote/none_auth_api_service.dart';
part 'package:aveoplayer/vid/yt/embed/android.dart';
part 'package:aveoplayer/vid/yt/embed/ios.dart';
part 'package:aveoplayer/vid/yt/custom/youtube_player.dart';
part 'package:aveoplayer/vid/yt/custom/helper/controller.dart';
part 'package:aveoplayer/vid/yt/custom/widgets/yt_controls.dart';
part 'package:aveoplayer/vid/yt/custom/widgets/playback_speed.dart';
part 'package:aveoplayer/vid/web_view_constructor.dart';
// part 'package:aveoplayer/vid/network/embed/android.dart';
// part 'package:aveoplayer/vid/assets/embed/android.dart';
